"""create Active-Chess learning core
Revision ID: 0001_active_learning_core
Revises:
"""
from alembic import op
import sqlalchemy as sa
revision='0001_active_learning_core'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users', sa.Column('id',sa.Integer,primary_key=True), sa.Column('username',sa.String(64),nullable=False), sa.Column('email',sa.String(255),nullable=False), sa.Column('hashed_password',sa.String(255),nullable=False), sa.Column('full_name',sa.String(255)), sa.Column('role',sa.String(32),nullable=False,server_default='student'), sa.Column('is_active',sa.Boolean,nullable=False,server_default=sa.true()), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()), sa.Column('updated_at',sa.DateTime(timezone=True)))
    op.create_index('ix_users_username','users',['username'],unique=True); op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('tracks', sa.Column('id',sa.Integer,primary_key=True), sa.Column('name',sa.String(120),nullable=False), sa.Column('slug',sa.String(120),nullable=False), sa.Column('description',sa.Text), sa.Column('icon',sa.String(32),server_default='♟️'), sa.Column('age_min',sa.Integer), sa.Column('age_max',sa.Integer), sa.Column('is_active',sa.Boolean,nullable=False,server_default=sa.true()), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now())); op.create_index('ix_tracks_slug','tracks',['slug'],unique=True)
    op.create_table('courses', sa.Column('id',sa.Integer,primary_key=True), sa.Column('track_id',sa.Integer,sa.ForeignKey('tracks.id',ondelete='CASCADE'),nullable=False), sa.Column('name',sa.String(160),nullable=False), sa.Column('slug',sa.String(160),nullable=False), sa.Column('description',sa.Text), sa.Column('fee',sa.Integer,server_default='0'), sa.Column('duration_months',sa.Integer,server_default='6'), sa.Column('is_published',sa.Boolean,nullable=False,server_default=sa.false()), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()), sa.Column('updated_at',sa.DateTime(timezone=True))); op.create_index('ix_courses_slug','courses',['slug'],unique=True)
    op.create_table('chapters', sa.Column('id',sa.Integer,primary_key=True), sa.Column('course_id',sa.Integer,sa.ForeignKey('courses.id',ondelete='CASCADE'),nullable=False), sa.Column('title',sa.String(160),nullable=False), sa.Column('description',sa.Text), sa.Column('order',sa.Integer,nullable=False,server_default='0'), sa.Column('is_published',sa.Boolean,nullable=False,server_default=sa.false()), sa.UniqueConstraint('course_id','order',name='uq_chapter_course_order'))
    op.create_table('lessons', sa.Column('id',sa.Integer,primary_key=True), sa.Column('chapter_id',sa.Integer,sa.ForeignKey('chapters.id',ondelete='CASCADE'),nullable=False), sa.Column('title',sa.String(180),nullable=False), sa.Column('description',sa.Text), sa.Column('content',sa.Text), sa.Column('order',sa.Integer,nullable=False,server_default='0'), sa.Column('lesson_type',sa.String(32),nullable=False,server_default='lesson'), sa.Column('is_published',sa.Boolean,nullable=False,server_default=sa.false()), sa.UniqueConstraint('chapter_id','order',name='uq_lesson_chapter_order'))
    op.create_table('enrollments', sa.Column('id',sa.Integer,primary_key=True), sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('course_id',sa.Integer,sa.ForeignKey('courses.id',ondelete='CASCADE'),nullable=False), sa.Column('status',sa.String(32),nullable=False,server_default='active'), sa.Column('enrolled_at',sa.DateTime(timezone=True),server_default=sa.func.now()), sa.UniqueConstraint('user_id','course_id',name='uq_enrollment_user_course'))
    op.create_table('lesson_progress', sa.Column('id',sa.Integer,primary_key=True), sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('lesson_id',sa.Integer,sa.ForeignKey('lessons.id',ondelete='CASCADE'),nullable=False), sa.Column('completed',sa.Boolean,nullable=False,server_default=sa.false()), sa.Column('score',sa.Integer,server_default='0'), sa.Column('attempts',sa.Integer,server_default='0'), sa.Column('completed_at',sa.DateTime(timezone=True)), sa.UniqueConstraint('user_id','lesson_id',name='uq_progress_user_lesson'))

def downgrade():
    for t in ['lesson_progress','enrollments','lessons','chapters','courses','tracks','users']: op.drop_table(t)
